Feat/productlist
apps-mvp/salesforce-integration pull request #3
Opened 2023-08-17 18:22 UTC by aka-sacci

Feat: Product list added, and deps.ts updated

2023-08-18 00:52 UTC, gustavo-vasconcellos requested changes

2023-08-18 00:52 UTC, gustavo-vasconcellos commented on app/loaders/product/productList.ts
> +  limit?: number;
isso tem que ser obrigatorio, o valor padrao pode ser 10 (`@default 10`)

2023-08-18 00:52 UTC, gustavo-vasconcellos commented on app/loaders/product/productList.ts
> +  return await toProductList(getProductBySlug, url.origin);
voce nao precisa de `await` aqui, toProductList nao é `async`

2023-08-18 00:52 UTC, gustavo-vasconcellos commented on app/utils/transform.ts
> +      productName,
Tudo bem ter um `toProductList`, voce vai usar nas paginas de categoria tambem. Mas cria um `toProduct` ppara poder usar na PDP tambem.

2023-08-18 00:52 UTC, gustavo-vasconcellos commented on app/utils/utils.ts
> +export const stringfyParams = (
**NUNCA** faça funçoes recursivas.
- Sao complexas
- Dificeis de entender
- Pecam muito em performance e gerenciamento de memoria

Me manda no discord onde que voce chama isso, tem isso tudo mas nao encontrei a chamada dessa funçao no loader 🤔

2023-08-18 23:18 UTC, aka-sacci commented on app/loaders/product/productList.ts
> +  limit?: number;
Feito

2023-08-18 23:18 UTC, aka-sacci commented on app/loaders/product/productList.ts
> +  return await toProductList(getProductBySlug, url.origin);
Removido

2023-08-18 23:19 UTC, aka-sacci commented on app/utils/transform.ts
> +      productName,
toProduct já existe nesse cara, da uma olhadinha mais pra baixo

2023-08-18 23:19 UTC, aka-sacci commented on app/utils/utils.ts
> +export const stringfyParams = (
Função recursiva removida, conforme solicitado

2023-08-18 23:20 UTC, aka-sacci commented on app/utils/utils.ts
> +export const stringfyParams = (
E código para transformação de objeto de parâmetros em parâmetros pra URL refatorado

2023-08-29 22:27 UTC, gustavo-vasconcellos approved these changes

2023-08-29 22:28 UTC, merged